import com.baeldung.spring.drools.model.TaxiRide;
import com.baeldung.spring.drools.model.Fare;

global com.baeldung.spring.drools.model.Fare rideFare;
global com.baeldung.spring.drools.service.HandleError handleError;

dialect  "mvel"

rule "Calculate Taxi Fare - Scenario 1"
    when
        TaxiRide(isNightSurcharge == false && distanceInMile >= 0 && distanceInMile < 10);
    then
       	rideFare.setNightSurcharge(0);
       	rideFare.setRideFare(70);
end

rule "Calculate Taxi Fare - Scenario 2"
    when
        TaxiRide(isNightSurcharge == true && distanceInMile >= 0 && distanceInMile < 10);
    then
       	rideFare.setNightSurcharge(30);
       	rideFare.setRideFare(70);
end

rule "Calculate Taxi Fare - Scenario Negative"
when
  taxiRideInstance:TaxiRide(distanceInMile < 0);
then
    handleError.handle(taxiRideInstance.getDistanceInMile(), hello("Bob"));
end

// rule "Calculate Taxi Fare - Scenario 3"
//     when
//         taxiRideInstance:TaxiRide(isNightSurcharge == false && distanceInMile >= 10 && distanceInMile < 100);
//     then
//        	rideFare.setNightSurcharge(0);
//        	rideFare.setRideFare(70+(2*taxiRideInstance.getDistanceInMile()));
// end


// rule "Calculate Taxi Fare - Scenario 4"
//     when
//         taxiRideInstance:TaxiRide(isNightSurcharge == true && distanceInMile >= 10 && distanceInMile < 100);
//     then
//        	rideFare.setNightSurcharge(30+taxiRideInstance.getDistanceInMile());
//        	rideFare.setRideFare(70+(2*taxiRideInstance.getDistanceInMile()));
// end


// rule "Calculate Taxi Fare - Scenario 5"
//     when
//         taxiRideInstance:TaxiRide(isNightSurcharge == false && distanceInMile >= 100);
//     then
//        	rideFare.setNightSurcharge(0);
//        	rideFare.setRideFare(70+(1.5*taxiRideInstance.getDistanceInMile()));
// end

// rule "Calculate Taxi Fare - Scenario 6"
//     when
//         taxiRideInstance:TaxiRide(isNightSurcharge == true && distanceInMile >= 100);
//     then
//        	rideFare.setNightSurcharge(30+taxiRideInstance.getDistanceInMile());
//        	rideFare.setRideFare(70+(1.5*taxiRideInstance.getDistanceInMile()));
// end
